
#Base urls
api.base.uri = http://localhost:9000/api
login.base.url = http://localhost:9000/login

#API endpoints
login.endpoint = http://localhost:9000/api/authenticate
bank.accounts.endpoint = http://localhost:9000/api/bank-accounts
delete.bank.account.endpoint = http://localhost:9000/api/bank-accounts


